name: CI/CD for publishing private packages

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      org_name:
        description: "Owner/Organization name"
        required: false
        type: string
        default: hoory-com
    secrets:
      GITHUB_PACKAGES_PAT:
        required: true
      PACKAGE_NAME:
        required: true
      PUBLISH_FOLDER:
        required: true

jobs:
  publish-gpr:
    name: Publish GPR
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]
        protoc-version: [3.14.0]

    steps:
      # Initialize
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ matrix.protoc-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Add private packages
      - name: Add private packages PAT
        run: |
          echo "@hoory-com:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_PACKAGES_PAT}}" > .npmrc
      - name: Extract private package list
        uses: sergeysova/jq-action@v2
        id: privatePackages
        with:
          cmd: "jq .branches.develop[] private-packages.json -r"
          multiline: true
      - name: Add Private packages
        run: |
          packages="${{ steps.privatePackages.outputs.value }}"
          for package in $packages; do
            version="latest"
            if [[ $package == *":"*  ]]; then
              packageAndVersion=(${package//:/ })
              package=${packageAndVersion[0]}
              version=${packageAndVersion[1]}
            fi
            echo $(jq --arg package "$package" --arg version "$version" '.devDependencies[$package]=$version' package.json | jq . ) > package.json
          done

      # Install
      - name: Install dependencies
        run: yarn install

      # Increase version and push to NPM
      - name: Increase the package version
        run: |
          PREV_VERSION=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_PACKAGES_PAT}}" \
            https://api.github.com/orgs/hoory-com/packages/npm/${{secrets.PACKAGE_NAME}}/versions?per_page=1 | jq '.[].name')
          NEXTVERSION=$(echo ${PREV_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}' | tr -d '"')
          echo $(jq --arg version "$NEXTVERSION" '.version=$version' package.json | jq . ) > package.json

      # Check format on CI
      - name: Check format
        run: yarn run format:check
        if: github.event.pull_request.merged == false

      # Build the app
      - name: Build package
        run: yarn run build

      # Publish it on NPM
      - name: Publish package
        if: github.event.pull_request.merged == true
        run: cd ${{ secrets.PUBLISH_FOLDER }} && npm publish

      - name: Delete old versions of package
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          keep: 5
          token: ${{ secrets.GITHUB_PACKAGES_PAT }}
          org_name: ${{ inputs.org_name }}
          names: |
            ${{ secrets.PACKAGE_NAME }}

  put-comment:
    needs: [publish-gpr]
    uses: hoory-com/workflows/.github/workflows/pr-comment.yaml@master
    with:
      COMMENT_TEXT: '<strong>${{ github.repository }}</strong> is published! 🥳️ [@sayjeyhi]'
