name: CI/CD for a static site

on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT:
        required: true
      GITHUB_PAT:
        required: true
      NPM_PACKAGES_PAT:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_ORG:
        required: true
      SENTRY_PROJECT:
        required: false
      DOMAIN:
        required: false
      TARGET_ENVIRONMENT:
        required: true

jobs:
  general:
    name: CI/CD
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}
      CI: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up gcloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install formatter
        run: yarn add global prettier --prefer-offline
        if: github.event.pull_request.merged == false

      - name: Check format
        run: yarn run format:check
        if: github.event.pull_request.merged == false

      - name: Extract private package list
        uses: sergeysova/jq-action@v2
        id: privatePackages
        with:
          cmd: 'jq .branches.$GITHUB_BASE_REF[] private-packages.json -r'
          multiline: true
      - name: Add private packages PAT
        run: |
          echo "@hoory-com:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${{secrets.NPM_PACKAGES_PAT}}" > .npmrc

      - name: Install dependencies
        run: yarn install

      - name: Install Private packages
        run: |
          packages="${{ steps.privatePackages.outputs.value }}"
          for package in $packages; do
            yarn add --frozen-lockfile $package
          done

      - name: Keep production environment variables file
        run: find . -name '.env.*' -not -name '.env.production' -delete

      # Change Deployment state to deploying
      - uses: chrnorm/deployment-action@releases/v1
        if: github.event.pull_request.merged == true
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.GITHUB_PAT }}"
          environment: "${{ secrets.TARGET_ENVIRONMENT }}"

      - name: Populate env variables
        run: node env.js ${{secrets.TARGET_ENVIRONMENT}}
        env:
          SENTRY_RELEASE_TAG: "${{ GITHUB_SHA }}"

      - name: Build app
        run: yarn run build

      - name: Upload the built application
        uses: "google-github-actions/upload-cloud-storage@v0"
        if: github.event.pull_request.merged == true
        with:
          path: "./build/"
          parent: false
          destination: "${{ secrets.DOMAIN }}"

      # Change Deployment state to success/failure
      - name: Update deployment status (success)
        if: github.event.pull_request.merged == true && success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ secrets.GITHUB_PAT }}"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: github.event.pull_request.merged == true && failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ secrets.GITHUB_PAT }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      # Keep sentry informed
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        if: github.event.pull_request.merged == true && SENTRY_PROJECT_NAME != ""
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ secrets.TARGET_ENVIRONMENT }}
          version: "${{ GITHUB_SHA }}"
          sourcemaps: "./build/js"
